namespace TOrgName.TMicroserviceInfrastructureRepositoryName.Pulumi.StackReferences.TIamEntraIdRepositoryNameStackReference;

internal sealed record ApplicationIdentity(string ApplicationClientId, string ServicePrincipalObjectId);
