namespace TOrgName.TContainerizationDeploymentRepositoryName.TMicroserviceRepositoryName.StackReferences.TIamAzureRepositoryNameStackReference;

internal sealed record ResourceGroup(string ResourceGroupName, 
    string ManagedIdentityId, string ManagedIdentityClientId, string ManagedIdentityPrincipalId);
