namespace TOrgName.TContainerizationRepositoryName.Pulumi.StackReferences.TIamEntraIdRepositoryNameStackReference;

internal sealed record ApplicationIdentity(string ApplicationClientId, string ServicePrincipalObjectId);
